### ISSUE TITLE
Overlap problem

### ISSUE THREAD

**Issue by kamilpogo** [kurkle/chartjs-chart-sankey#88]
I created an example where the flows overlap: https://codesandbox.io/s/blazing-dawn-b07djs?file=/src/index.js
The node with the name "bug" has a wrong position. Do you see a way how to fix this except adding more nodes?

**Comment by kurkle** [comment]
No, I don't see a way of fixing it just by configuration :/

**Comment by hanstar17** [comment]
@richardtallent-erm What about this one? why is Net Income gone down?
![Screenshot 2023-04-28 at 10 10 48 PM](https://user-images.githubusercontent.com/5125332/235284779-f88b75f5-b7d6-4f7e-b668-738c3ff1714a.png)

**Comment by uberhus** [comment]
I guess I'm writing about the same issue here: https://github.com/kurkle/chartjs-chart-sankey/discussions/108

Maybe I could solve it by creating additional flow/nodes for the links that overlap (continuing the flow with the same value so that there would be an even amount of nodes on all levels), but that would look kind of silly, especially with the gradients and highlighted nodes. 

I wouldn't mind if the nodes would end earlier, like in the sankey here: 
![image](https://github.com/kurkle/chartjs-chart-sankey/assets/34740599/e0641d89-512d-4019-9217-75db2ea20cc0)

Maybe a quick way to do that would be to add a possibility to create invisible links/nodes, for example if you set this in @hanstar17 's chart above:

{from: "Income Tax": to: null, flow: null} 

The "Income Tax" node would end at the same level as "Net Income" and there would be an invisible node after the "Income Tax" which wouldn't show any info. At the moment even if you set the flow to 0 it still draws a line.
